### ISSUE TITLE
clicking on view expense

### ISSUE THREAD

**Issue by ComputerScientist-01** [sandip2224/E-Wallet-X#2]
![bug](https://user-images.githubusercontent.com/39644109/133916418-4aa1af2f-be02-46b3-b7e9-5cbceaf02159.png)
when clicking on view expense: it shows it as expense added successfully

**Comment by sandip2224** [comment]
Ah great thanks for raising an issue. I've added a fix for it. Can you check?

**Comment by ComputerScientist-01** [comment]
it is fine now

**Comment by sandip2224** [comment]
Ok great.
